name: Close Stale PRs

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  close-stale-prs:
    runs-on: ubuntu-latest

    steps:
      - name: Close Stale PRs
        uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          days-before-stale: 30
          days-before-close: 0
          stale-pr-message: 'This PR has been automatically marked as stale due to inactivity for 30 days. It will now be closed.'
          close-pr-message: 'This PR is being closed due to inactivity for 30 days.'
          stale-issue-message: ''
          close-issue-message: ''
          only-labels: ''
          exempt-issue-labels: '*'
          stale-issue-label: 'stale'
          exempt-pr-labels: ''
